[package]
name = "ffbc"
version = "0.1.0"
authors = ["Sebastian Berntsson <sebastianberntsson@users.noreply.github.com>"]

[dependencies.rustc-serialize]
git = "https://github.com/rust-lang/rustc-serialize.git"
